### ISSUE TITLE
Build (jank-configure) failure on M1 mac

### ISSUE THREAD

**Issue by PEZ** [jeaye/jank#9]
I got this when trying to run this on my Macbook Pro M1.

```
[nix-shell:~/Projects/jank]$ jank-configure
The Meson build system
Version: 0.61.2
Source dir: /Users/pez/Projects/jank
Build dir: /Users/pez/Projects/jank/build
Build type: native build
Project name: jank
Project version: snapshot
C++ compiler for the host machine: clang++ (clang 11.1.0 "clang version 11.1.0")
C++ linker for the host machine: clang++ ld64 530
Host machine cpu family: aarch64
Host machine cpu: arm64

meson.build:8:0: ERROR: Include dir lib/magic_enum/include does not exist.

A full log can be found at /Users/pez/Projects/jank/build/meson-logs/meson-log.txt
```

Please let me know if I can provide any further detail. Or if I can make any experiments that would help you understand what's going on (or not).

**Comment by jeaye** [comment]
Hi! Thanks for your interest and for reaching out. This is the same error as described here: #7 

Just a missing build step, actually. :) But please read that linked issue to understand the current state of jank's buildability on arbitrary machines.
